# Generated by Django 5.2 on 2025-04-27 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groza_list', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoppingitem',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shoppinglist',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
